[project]
name = "discord-telegram-voice-bot"
version = "0.1.0"
dependencies = [
  "discord.py",
  "requests",
  "python-dotenv"
]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
